all:
  hosts:
    kube0:
      ansible_host: 192.168.1.10
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.10
    kube1:
      ansible_host: 192.168.1.11
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.11
  children:
    kube_control_plane:
      hosts:
        kube0:
    kube_node:
      children:
        kube0:
        kube1:
    etcd:
      hosts:
        kube0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    cloud_storage:
      hosts: {}
