all:
  hosts:
    kube1:
      ansible_host: 192.168.2.101
      ansible_user: ubuntu
      ip: 192.168.2.101
    kube2:
      ansible_host: 192.168.2.102
      ansible_user: ubuntu
      ip: 192.168.2.102
  children:
    kube_control_plane:
      hosts:
        kube1:
    kube_node:
      hosts:
        kube1:
        kube2:
    etcd:
      hosts:
        kube1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    cloud_storage:
      hosts: {}
