all:
  hosts:
    kube0:
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.10
    kube1:
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.11
    kube3:
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.12
    kube4:
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.13
    # kube5:
    #   ansible_host: kube5.home
    #   ansible_user: ubuntu
    #   ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    #   ip: 192.168.1.14
    kube6:
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.15
    # kube7:
    #   ansible_host: kube7.home
    #   ansible_user: ubuntu
    #   ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    #   ip: 192.168.1.16
  children:
    kube_control_plane:
      hosts:
        kube0:
    amd64nodes:
      hosts:
        kube0:
        kube1:
    arm64nodes:
      hosts:
        kube3:
        kube4:
        # kube5:
        kube6:
        # kube7:
    kube_node:
      hosts:
        kube0:
        kube1:
        kube3:
        kube4:
        # kube5:
        kube6:
        # kube7:
    etcd:
      hosts:
        kube0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    cloud_storage:
      hosts: {}
