all:
  hosts:
    kube0:
      ansible_host: 192.168.1.10
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.10
    kube1:
      ansible_host: 192.168.1.11
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.11
    kube3:
      ansible_host: 192.168.1.12
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.12
    kube4:
      ansible_host: 192.168.1.13
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.13
    kube5:
      ansible_host: 192.168.1.14
      ansible_user: ubuntu
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      ip: 192.168.1.14
    # kube6:
    #   ansible_host: 192.168.1.15
    #   ansible_user: ubuntu
    #   ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    #   ip: 192.168.1.15
    # kube7:
    #   ansible_host: 192.168.1.16
    #   ansible_user: ubuntu
    #   ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    #   ip: 192.168.1.16
  children:
    kube_control_plane:
      hosts:
        kube0:
    amd64nodes:
      hosts:
        kube0:
        kube1:
    arm64nodes:
      hosts:
        kube3:
        kube4:
        kube5:
        # kube6:
        # kube7:
    kube_node:
      children:
        arm64nodes:
        amd64nodes:
    etcd:
      hosts:
        kube0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    cloud_storage:
      hosts: {}
