storage:
  - name: onpremise
    hostname: my-onpremise-hostname
    mount_path: /var/lib/mounts
    folders:
      - name: backups
        backup: true
      - name: dynamic
        backup: true
      - name: syncthing
        syncthing: true
  - name: cloud
    hostname: myNodeName
    mount_path: /var/lib/mounts
    folders:
      - name: dynamic
        backup: true
      - name: syncthing
        syncthing: true
        backup: true
      - name: media
        google: true
        fixed: true
      - name: downloads
        fixed: true

tasks:
  secrets:
    image: registry.yusufali.ca/elrond/helper
    rclone: rclone
    scripts: rclone-scripts
  configs:
    - name: backup
      command: 
        - python3
      args:
        - mycommand
      env: {}
    - name: sync
      command:
        - python3
      args:
        - blahblah

spec:
  project: myproject
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

templateSource:
  path: charts/helm
  repoURL: https://github.com/drgroot/kubespray.git
  targetRevision: HEAD

versions:
  nfs_server: 
    image: itsthenetwork/nfs-server-alpine
    tag: "12"
  nfs_provisioner: "4.0.17"
  syncthing:
    semvar: "~1"
    tag: "1.20.4"