storage:
  - name: onpremise
    hostname: my-onpremise-hostname
    folders:
      - name: backups
        backup: true
        mountPath: /var/lib/mounts
      - name: dynamic
        backup: true
      - name: syncthing
        syncthing: true
  - name: cloud
    hostname: myNodeName
    folders:
      - name: dynamic
        backup: true
      - name: syncthing
        syncthing: true
        backup: true
      - name: media
        google: true
        fixed: true
      - name: downloads
        fixed: true

secretStore:
  name: asdasd
  kind: ClusterSecretStore

secrets:
  rclone:
    data:
      - key: RCLONE
        property: rclone.conf
tasks: []

spec:
  project: myproject
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

templateSource:
  path: charts/helm
  repoURL: https://github.com/drgroot/kubespray.git
  targetRevision: HEAD

versions:
  nfs_provisioner: "4.0.17"
