storage:
  - name: onpremise
    hostname: my-onpremise-hostname
    mount_path: /var/lib/mounts
    folders:
      - name: backups
        backup: true
      - name: dynamic
        backup: true
      - name: syncthing
        syncthing: true
  - name: cloud
    hostname: myNodeName
    mount_path: /var/lib/mounts
    folders:
      - name: dynamic
        backup: true
      - name: syncthing
        syncthing: true
        backup: true
      - name: media
        google: true
        fixed: true
      - name: downloads
        fixed: true

secretStore:
  name: asdasd
  kind: ClusterSecretStore

secrets:
  rclone:
    data:
      - key: RCLONE
        property: rclone.conf
  # private:
  #   type: kubernetes.io/dockerconfigjson
  #   template:
  #     .dockerconfigjson: |
  #       {
  #         "auths": {
  #           "https://registry.yusufali.ca": {
  #             "auth": {{ b64enc (print .USERNAME ":" .PASSWORD ) | quote }}
  #           }
  #         }
  #       }
  #   data:
  #     - name: USERNAME
  #       key: DOCKER
  #       property: PRIVATE_USERNAME
  #     - name: PASSWORD
  #       key: DOCKER
  #       property: PRIVATE_PASSWORD

imageSecrets:
  chart: []
    # - public
    # - private
  external: []

tasks:
  image: rclone/rclone
  configs:
    - name: backup
      command:
        - python3
      args:
        - mycommand
      env: {}
    - name: sync
      command:
        - python3
      args:
        - blahblah

spec:
  project: myproject
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

templateSource:
  path: charts/helm
  repoURL: https://github.com/drgroot/kubespray.git
  targetRevision: HEAD

versions:
  nfs_provisioner: "4.0.17"
