apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      automountServiceAccountToken: true
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.initContainers .Values.pvc.backup.enabled }}
      initContainers:
      {{- if .Values.pvc.backup.enabled }}
        - name: restore
          image: {{ .Values.pvc.backup.image }}
          imagePullPolicy: Always
          {{- with default .Values.pvc.backup.securityContext .Values.securityContext  }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.pvc.name}}
              mountPath: /backup
              readOnly: true
            {{- range .Values.pvc.backup.volumeMounts }}
            - name: {{ $.Values.pvc.name}}-emp
{{ toYaml . | nindent 14 }}
            {{- end }} 
          env:
          {{- with .Values.pvc.backup.env }}
{{ toYaml . | indent 12 }}
          {{- end }}
        {{- end }}
        {{- with .Values.initContainers }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.name }}:{{ .Values.image.prefix }}{{ .Values.image.tag | default .Chart.AppVersion }}{{ .Values.image.suffix }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
{{ toYaml . | nindent 12 }}
          {{- end }}
{{- with .Values.args }}
          args:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ports }}
          ports:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.volumeMounts .Values.pvc.backup.enabled }}
          volumeMounts:
            {{- if .Values.pvc.backup.enabled }}
            {{- range .Values.pvc.backup.volumeMounts }}
            - name: {{ $.Values.pvc.name}}-emp
{{ toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
          {{- with .Values.volumeMounts }}
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.probes }}
{{ toYaml . | indent 10 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.pvc.backup.enabled }}
        - name: backup
          image: {{ .Values.pvc.backup.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.pvc.backup.port }}
              protocol: TCP
              name: backuphttpport
          {{- with default .Values.pvc.backup.securityContext .Values.securityContext  }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- range .Values.pvc.backup.volumeMounts }}
            - name: {{ $.Values.pvc.name}}-emp
{{ toYaml . | nindent 14 }}
          {{- end }} 
          env:
            - name: SERVER
              value: "enable"
            - name: PORT
              value: {{ .Values.pvc.backup.port | quote }}
          {{- with .Values.pvc.backup.env }}
{{ toYaml . | indent 12 }}
          {{- end }}
        {{- end }}
        {{- with .Values.sideCars }}
{{ toYaml . | indent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.pvc.enabled }}
        - name: {{ .Values.pvc.name}}
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-pvc
      {{- end }}
      {{- if .Values.pvc.backup.enabled }}
        - name: {{ .Values.pvc.name}}-emp
          emptyDir:
            sizeLimit: {{ .Values.pvc.storage }}
      {{- end }}
      {{- with .Values.volumes }}
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
