defaultClassName: pvcclassname

spec:
  project: myproject
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

templateSource:
  path: charts/helm
  repoURL: https://github.com/drgroot/kubespray.git
  targetRevision: HEAD

tools: []
  # - name: drone
  #   namespace: mynamespace
  #   serviceAccount: my-sa
  #   image:
  #     name: drone-image
  #     semvar: v1
  #     tag: "1.2"
  #   url: http://mydrone.com
  #   secrets: 
  #     - my-drone-secret
  #   ports:
  #     - port: 80
  #       protocol: TCP
  #   env:
  #     - name: NAMESPACE
  #       value: mynamespace
  #   resources:
  #     memory: 1Gi
  #   ingress:
  #     annotations:
  #       stuff: stuff
  #   volumes:
  #     - mountPath: /config
  #       subPath: asd