{{- range $pvcName, $config := .Values.storage }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "servc.fullname" $ }}-{{ $pvcName }}
  labels:
    {{- include "servc.labels" $ | nindent 4 }}
    {{- with $.Values.globals.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    type: pvc
    component: pvc
    pvc: {{ $pvcName }}
spec:
  accessModes:
    - {{ $config.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ $config.size | default "5Gi" }}
  storageClassName: {{ $config.storageClass | default "default" }}
---
{{- end }}
{{- end }}
{{- range $componentType, $components := .Values.components }}
{{- range $component, $config := $components.list }}
{{ $config := mustMergeOverwrite (deepCopy $.Values.globals) (deepCopy $components.globals) $config }}
{{- if and (not (((($config.storage).config).backup).enabled)) ((($config.storage).config).enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "servc.fullname" $ }}-{{ $componentType }}-{{ $component }}-config
  labels:
    {{- include "servc.labels" $ | nindent 4 }}
    {{- with $config.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    type: pvc
    component: config
    config: {{ $component }}
spec:
  accessModes:
    - {{ (($config.storage).config).accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ (($config.storage).config).size | default "5Gi" }}
  storageClassName: {{ (($config.storage).config).storageClass| default "default" }}
---
{{- end }}
{{- end }}
{{- end }}