---
- name: Install softare
  hosts: all
  tasks:
    - name: install nfs, fuse, and ufw software
      ansible.builtin.apt:
        name:
          # - fuse
          - nfs-common
          # - ufw
          # - open-iscsi
          - jq
        state: latest
- name: Install kubectl software
  hosts: kube_control_plane
    - name: install kubectl
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 0555
    # - name: enable iscsid
    #   ansible.builtin.service:
    #     name: iscsid
    #     state: started
    #     enabled: true
