spec:
  project: myproject
  destination:
    server: https://kubernetes.default.svc
    project: bootstrap

  source:
    url: https://github.com/drgroot/kubespray.git
    revision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

templateSource:
  path: charts/helm
  repoURL: https://github.com/drgroot/kubespray.git
  targetRevision: HEAD

secrets:
  cloudflare_domain:
    key: CLOUDFLARE
    property: CLOUDFLARE_PERSONAL_DOMAIN_NAME
  cloudflare_api:
    key: CLOUDFLARE
    property: CLOUDFLARE_PERSONAL_API_KEY

htpasswdTemplate:
  htpasswd: |-
    {{ htpasswd .PRIVATE_USERNAME .PRIVATE_PASSWORD }}
dockerconfigTemplate:
  .dockerconfigjson: |
    {
      "auths": {
        {{ print .HOST | quote }}: {
          "auth": {{ b64enc (print .USERNAME ":" .PASSWORD ) | quote }}
        }
      }
    }

stores:
  - name: external
    username: external-username
    secretName: my-secret
    namespace: default
    server: http://external.com
    kind: SecretStore
    path: external-infra

externalsecrets:
  version: 0.7.0
  namespace: externalsecrets

postgres:
  shmSize: 512Mi
  namespace: default
  replicaCount: 3
  storageClass: default
  backupStorageClass: default
  secret:
    postgres: asd
    pgpool: asda
  resources:
    requests:
      memory: 1Gi
      cpu: 512m

rabbitmq:
  releaseName: rabbitmq
  namespace: default
  replicaCount: 3
  storageClass: default
  resources: {}

coder:
  releaseName: coder
  namespace: default
  version: 1.21.0
  workspaces:
    namespace: workspaces
  pvcs: []

gitea:
  namespace: default