spec:
  project: myproject
  destination:
    server: https://kubernetes.default.svc
    project: bootstrap

  source:
    url: https://github.com/drgroot/kubespray.git
    revision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

templateSource:
  path: charts/helm
  repoURL: https://github.com/drgroot/kubespray.git
  targetRevision: HEAD

secrets:
  cloudflare_domain:
    key: CLOUDFLARE
    property: CLOUDFLARE_PERSONAL_DOMAIN_NAME
  cloudflare_api:
    key: CLOUDFLARE
    property: CLOUDFLARE_PERSONAL_API_KEY

dockerconfigTemplate:
  .dockerconfigjson: |
    {
      "auths": {
        {{ print .HOST | quote }}: {
          "auth": {{ b64enc (print .USERNAME ":" .PASSWORD ) | quote }}
        }
      }
    }

externalsecrets:
  version: 0.7.0
  namespace: externalsecrets
  stores:
    vault:
      server: http://vault.com
      secretStore:
        name: my-cluster-secretstore
        username: vault-username
        secretRef:
          name: vault-secret-name
          namespace: my-namespace
          key: PASSWORD

postgres:
  shmSize: 512Mi
  namespace: default
  replicaCount: 3
  storageClass: default
  backupStorageClass: default
  secret:
    postgres: asd
    pgpool: asda
  resources:
    requests:
      memory: 1Gi
      cpu: 512m

rabbitmq:
  releaseName: rabbitmq
  namespace: default
  replicaCount: 3
  storageClass: default
  resources: {}

coder:
  releaseName: coder
  namespace: default
  version: 1.21.0
  workspaces:
    namespace: workspaces
  pvcs: []
