{{- if .Values.secrets.pushsecret.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ include "postgres.fullname" . }}-credentials
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  secretStoreRefs:
    - name: {{ .Values.secrets.pushsecret.secretStore.name }}
      kind: {{ .Values.secrets.pushsecret.secretStore.type }}
  selector:
    secret:
      name: {{ include "postgres.fullname" . }}-credentials
  data:
    - conversionStrategy: None
      match:
        secretKey: url
        remoteRef:
          remoteKey: {{ .Values.secrets.pushsecret.remoteKey }}
          property: url
    - conversionStrategy: None
      match:
        secretKey: password
        remoteRef:
          remoteKey: {{ .Values.secrets.pushsecret.remoteKey }}
          property: password
    - conversionStrategy: None
      match:
        secretKey: username
        remoteRef:
          remoteKey: {{ .Values.secrets.pushsecret.remoteKey }}
          property: username
    - conversionStrategy: None
      match:
        secretKey: database
        remoteRef:
          remoteKey: {{ .Values.secrets.pushsecret.remoteKey }}
          property: database
    - conversionStrategy: None
      match:
        secretKey: hostname
        remoteRef:
          remoteKey: {{ .Values.secrets.pushsecret.remoteKey }}
          property: hostname
{{- end }}
