apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "postgres.fullname" . }}-credentials
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.secrets.secretStore.name }}
    kind: {{ .Values.secrets.secretStore.type }}
  target:
    name: {{ include "postgres.fullname" . }}-credentials
    template:
      engineVersion: v2
      data:
        username: '{{ `{{ .USERNAME }}` }}'
        password: '{{ `{{ .PASSWORD }}` }}'
        database: {{ .Values.database | quote }}
        hostname: {{ include "postgres.hostname" . | quote }}
        url: 'postgres://{{ `{{ .USERNAME }}` }}:{{ `{{ .PASSWORD }}` }}@{{ include "postgres.hostname" . }}/{{ .Values.database }}'
  data:
    - secretKey: USERNAME
      remoteRef:
        key: {{ .Values.secrets.username.remoteRef.key }}
        property: {{ .Values.secrets.username.remoteRef.property }}
    - secretKey: PASSWORD
      remoteRef:
        key: {{ .Values.secrets.password.remoteRef.key }}
        property: {{ .Values.secrets.password.remoteRef.property }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "postgres.fullname" . }}-rclone
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.backup.secretStore.name }}
    kind: {{ .Values.backup.secretStore.type }}
  target:
    name: {{ include "postgres.fullname" . }}-rclone
  data:
    - secretKey: rclone.conf
      remoteRef:
        key: {{ .Values.backup.rclone.remoteRef.key }}
        property: {{ .Values.backup.rclone.remoteRef.property }}
