apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-postgres-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-infra
    kind: ClusterSecretStore
  target:
    name: memos-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef: {key: iac/postgres-memos, property: username}
    - secretKey: password
      remoteRef: {key: iac/postgres-memos, property: password}
    - secretKey: hostname
      remoteRef: {key: iac/postgres-memos, property: hostname}
    - secretKey: database
      remoteRef: {key: iac/postgres-memos, property: database}
    - secretKey: schema
      remoteRef: {key: iac/postgres-memos, property: schema}
    - secretKey: url
      remoteRef: {key: iac/postgres-memos, property: url}
