apiVersion: v1
kind: Service
metadata:
  name: comfyui
spec:
  ports:
    - name: http
      port: 8189
      targetPort: 8189
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: comfyui
  labels:
    kubernetes.io/service-name: comfyui
    endpointslice.kubernetes.io/managed-by: gitops
addressType: IPv4
ports:
  - name: http
    port: 8189
    protocol: TCP
endpoints:
  - addresses:
      - "192.168.1.144"
    conditions:
      ready: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfyui
  annotations:
    external-dns.alpha.kubernetes.io/target: mordorhome.{{ .Values.domains.external }}
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-url: http://authelia.kube-platform.svc.cluster.local/api/authz/auth-request
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.{{ .Values.domains.external }}?rm=$request_method"
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - comfyui.{{ .Values.domains.external }}
      secretName: wildcard-tls
  rules:
    - host: comfyui.{{ .Values.domains.external }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: comfyui
                port:
                  name: http
