instances: 1
imageName: ghcr.io/cloudnative-pg/postgresql:16.3

postgresUID: 26
postgresGID: 26

storage:
  size: 10Gi
  storageClass: default
backup:
  storageClass: default
  schedule: "0 0 * * *"

bootstrap:
  database: postgres
  username: app
  secretName: password
  postgresInit: []

roles: []

shared_buffers: 128MB
resources: {}

pushSecret:
  enabled: false
  secretstore: ""
  remoteKey: ""
