apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  secretStoreRef:
    name: external-infra
    kind: ClusterSecretStore
  target:
    name: tenant-repo-credentials
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: https://git.yusufali.ca/
        username: '{{ printf "{{ .USERNAME }}" }}'
        password: '{{ printf "{{ .PASSWORD }}" }}'
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: GIT
        property: GIT_PASSWORD
    - secretKey: USERNAME
      remoteRef:
        key: GIT
        property: GIT_USERNAME