apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cluster-docker-secrets
spec:
  externalSecretName: cluster-docker-secrets
  namespaceSelectors:
    - matchLabels:
        tenant: approved
  externalSecretSpec:
    secretStoreRef:
      name: external-infra
      kind: ClusterSecretStore
    target:
      name: cluster-docker-secrets
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "registry-1.docker.io": {
                  "auth": {{ `{{ b64enc (print .USERNAME_PRIVATE ":" .PASSWORD_PRIVATE ) | quote }}` }}
                },
                "dockerhub.{{ .Values.domains.external }}": {
                  "auth": {{ `{{ b64enc (print .USERNAME_MIRROR ":" .PASSWORD_MIRROR ) | quote }}` }}
                },
                "https://dockerhub.{{ .Values.domains.external }}": {
                  "auth": {{ `{{ b64enc (print .USERNAME_MIRROR ":" .PASSWORD_MIRROR ) | quote }}` }}
                },
                {{ `{{ print .HOST_PRIVATE | quote }}` }}: {
                  "auth": {{ `{{ b64enc (print .USERNAME_PRIVATE ":" .PASSWORD_PRIVATE ) | quote }}` }}
                }
              }
            }
    data:
      - remoteRef:
          key: vendor/docker
          property: private-username
        secretKey: USERNAME_PRIVATE
      - remoteRef:
          key: vendor/docker
          property: private-password
        secretKey: PASSWORD_PRIVATE
      - remoteRef:
          key: vendor/docker
          property: private-host
        secretKey: HOST_PRIVATE
      - remoteRef:
          key: vendor/docker
          property: mirror-username
        secretKey: USERNAME_MIRROR
      - remoteRef:
          key: vendor/docker
          property: mirror-password
        secretKey: PASSWORD_MIRROR
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cluster-smtp-secrets
spec:
  externalSecretName: cluster-smtp-secrets
  namespaceSelectors:
    - matchLabels:
        tenant: approved
  externalSecretSpec:
    secretStoreRef:
      name: external-infra
      kind: ClusterSecretStore
    target:
      name: cluster-smtp-secrets
    data:
      - remoteRef:
          key: vendor/smtp
          property: host
        secretKey: SMTP_HOST
      - remoteRef:
          key: vendor/smtp
          property: password
        secretKey: SMTP_PASSWORD
      - remoteRef:
          key: vendor/smtp
          property: port
        secretKey: SMTP_PORT
      - remoteRef:
          key: vendor/smtp
          property: security
        secretKey: SMTP_SECURITY
      - remoteRef:
          key: vendor/smtp
          property: username
        secretKey: SMTP_USERNAME
      - remoteRef:
          key: vendor/smtp
          property: from-domain
        secretKey: SMTP_FROM_DOMAIN
      - remoteRef:
          key: vendor/smtp
          property: from-email
        secretKey: SMTP_FROM_EMAIL
      - remoteRef:
          key: vendor/smtp
          property: from-user
        secretKey: SMTP_FROM_USER
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cluster-middleware-secrets
spec:
  externalSecretName: cluster-middleware-secrets
  namespaceSelectors:
    - matchLabels:
        tenant: approved
        client: t
  externalSecretSpec:
    secretStoreRef:
      name: external-infra
      kind: ClusterSecretStore
    target:
      name: cluster-middleware-secrets
    data:
      - remoteRef:
          key: iac/redis
          property: hostname
        secretKey: redishostname
      - remoteRef:
          key: iac/redis
          property: url
        secretKey: redisurl
