---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pull
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ .Values.storage.nobackup }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-pull
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-pull
  template:
    metadata:
      labels:
        app: docker-pull
    spec:
      containers:
        - name: app
          image: {{ .Values.registry.image.registry }}{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}
          env:
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: registry-htpasswd
                  key: htpasswd
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_PROXY_REMOTEURL
              value: https://registry-1.docker.io
            - name: REGISTRY_PROXY_TTL
              value: 168h
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          resources:
            {{- with.Values.registry.resources }}
            requests:
              {{- toYaml . | nindent 14 }}
            limits:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          ports:
            - containerPort: 5000
              name: port-5000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/registry
              name: config
            - mountPath: /auth
              name: htpasswd
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: docker-pull
        - name: htpasswd
          secret:
            defaultMode: 420
            secretName: registry-htpasswd
---
apiVersion: v1
kind: Service
metadata:
  name: docker-pull
spec:
  ports:
    - name: port-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: docker-pull
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: mordorhome.{{ .Values.domains.external }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5000m
    nginx.ingress.kubernetes.io/proxy-body-size: 5000m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: docker-pull
spec:
  ingressClassName: nginx
  rules:
    - host: dockerhub.{{ .Values.domains.external }}
      http:
        paths:
          - backend:
              service:
                name: docker-pull
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - '*.{{ .Values.domains.external }}'
      secretName: wildcard-external
