apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-htpasswd
spec:
  secretStoreRef:
    name: external-infra
    kind: ClusterSecretStore
  target:
    name: registry-htpasswd
    template:
      type: Opaque
      data:
        htpasswd: '{{ `{{ htpasswd .PRIVATE_USERNAME .PRIVATE_PASSWORD "bcrypt" }}` }}'
  data:
    - remoteRef:
        key: vendor/docker
        property: private-username
      secretKey: PRIVATE_USERNAME
    - remoteRef:
        key: vendor/docker
        property: private-password
      secretKey: PRIVATE_PASSWORD
---