{{- range $sync := .Values.secretSync }}
{{- $name := printf "secret-sync-%s" $sync.name }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
spec:
  secretStoreRef:
    kind: {{ $sync.input.kind }}
    name: {{ $sync.input.name }}
  target:
    name: {{ $name }}
    creationPolicy: Owner
  data:
  {{- range $property := $sync.input.properties }}
    - secretKey: {{ $property }}
      remoteRef:
        key: {{ $sync.input.path }}
        property: {{ $property }}
  {{- end }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $name }}
spec:
  {{- with $sync.output.updatePolicy }}
  updatePolicy: {{ . }}
  {{- end }}
  secretStoreRefs:
    - kind: {{ $sync.output.kind }}
      name: {{ $sync.output.name }}
  selector:
    secret:
      name: {{ $name }}
  data:
  {{- range $inputProperty, $outputProperty := $sync.output.properties }}
    - conversionStrategy: None
      match:
        secretKey: {{ $inputProperty }}
        remoteRef:
          remoteKey: {{ $sync.output.path }}
          property: {{ $outputProperty }}
  {{- end }}
{{- end }}
