---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - image: tabulario/iceberg-rest
          name: app
          ports:
            - containerPort: 8181
              protocol: TCP
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-root-credential
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-root-credential
                  key: secretkey
            - name: AWS_SECRET_ACCESS_KEY
              value: password
            - name: AWS_REGION
              value: us-east-1
            - name: CATALOG_WAREHOUSE
              value: s3://{{ .Values.storageClass.warehouse }}
            - name: CATALOG_IO__IMPL
              value: org.apache.iceberg.aws.s3.S3FileIO
            - name: CATALOG_S3_ENDPOINT
              value: https://s3.{{ .Values.domains.external }}
            - name: CATALOG_DEFAULT__NAMESPACE
              value: default
            - name: CATALOG_JDBC_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-postgres-credentials
                  key: username
            - name: CATALOG_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-root-credential
                  key: password
            - name: POSTGRES_DATABASE
              valueFrom: 
                secretKeyRef:
                  name: catalog-postgres-credentials
                  key: database
            - name: POSTGRES_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: catalog-postgres-credentials
                  key: hostname
            - name: CATALOG_URI
              value: jdbc:postgresql://$(POSTGRES_HOSTNAME)/$(POSTGRES_DATABASE)
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  ports:
    - name: web
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: catalog
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 512m
    nginx.ingress.kubernetes.io/client_max_body_size: 512m
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: mordorhome.{{ .Values.domains.external }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - '*.{{ .Values.domains.external }}'
      - '*.s3.{{ .Values.domains.external }}'
      secretName: wildcard-external
  ingressClassName: nginx
  rules:
    - host: catalog.{{ .Values.domains.external }}
      http:
        paths:
          - backend:
              service:
                name: catalog
                port:
                  number: 8181
            path: /
            pathType: Prefix
