apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: catalog-root-credential
spec:
  secretStoreRef:
    name: external-infra
    kind: ClusterSecretStore
  target:
    name: catalog-root-credential
  data:
    - secretKey: password
      remoteRef:
        key: DB_POSTGRES
        property:  PASSWORD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-postgres
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.project }}
  source:
    path: "charts/postgres"
    repoURL: "https://github.com/drgroot/kubespray.git"
    targetRevision: HEAD
    helm:
      releaseName: catalog-postgres
      values: |-
        fullnameOverride: catalog-postgres

        storageclass: {{ .Values.storage.ssd }}

        backup:
          storageclass: {{ .Values.storage.backup }}

        server:
          password:
            secretname: catalog-root-credential
          additionalUsers: []

        pushsecret:
          enabled: false
          remoteKey: catalog-postgres-credentials
---