apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: lake-pushsecret
spec:
  secretStoreRefs:
    - name: kubernetes
      kind: ClusterSecretStore
  selector:
    secret:
      name: s3-root-credential
  template:
    data:
      namespace: default
      uri: http://catalog.{{ .Release.Namespace }}:8181
      warehouse: s3://{{ .Values.storageClass.warehouse }}
      s3endpoint: https://s3.{{ .Values.domains.external }}
      s3region: us-east-1
      s3accesskey: "{{ `{{ .accesskey }}` }}"
      s3secretkey: "{{ `{{ .secretkey }}` }}"
  data:
    - conversionStrategy: None
      match:
        secretKey: s3secretkey
        remoteRef:
          remoteKey: datalake
          property: s3secretkey
    - conversionStrategy: None
      match:
        secretKey: s3accesskey
        remoteRef:
          remoteKey: datalake
          property: s3accesskey
    - conversionStrategy: None
      match:
        secretKey: s3region
        remoteRef:
          remoteKey: datalake
          property: s3region
    - conversionStrategy: None
      match:
        secretKey: namespace
        remoteRef:
          remoteKey: datalake
          property: namespace
    - conversionStrategy: None
      match:
        secretKey: uri
        remoteRef:
          remoteKey: datalake
          property: uri
    - conversionStrategy: None
      match:
        secretKey: warehouse
        remoteRef:
          remoteKey: datalake
          property: warehouse
    - conversionStrategy: None
      match:
        secretKey: s3endpoint
        remoteRef:
          remoteKey: datalake
          property: s3endpoint