apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: lake-pushsecret
spec:
  secretStoreRefs:
    - name: kubernetes
      kind: ClusterSecretStore
  selector:
    secret:
      name: catalog-postgres-credentials
  template:
    data:
      namespace: default
      uri: http://catalog.{{ .Release.Namespace }}:8181
      warehouse: s3://servc
      s3endpoint: http://seaweedfs-s3.{{ .Release.Namespace }}:8333
  data:
    - conversionStrategy: None
      match:
        secretKey: namespace
        remoteRef:
          remoteKey: datalake
          property: namespace
    - conversionStrategy: None
      match:
        secretKey: uri
        remoteRef:
          remoteKey: datalake
          property: uri
    - conversionStrategy: None
      match:
        secretKey: warehouse
        remoteRef:
          remoteKey: datalake
          property: warehouse
    - conversionStrategy: None
      match:
        secretKey: s3endpoint
        remoteRef:
          remoteKey: datalake
          property: s3endpoint