---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.project }}
  source:
    chart: seaweedfs
    repoURL: https://seaweedfs.github.io/seaweedfs/helm
    targetRevision: 4.0.379
    helm:
      releaseName: s3
      values: |-
        global:
          createClusterRole: false
          automountServiceAccountToken: false

        master:
          replicas: 1

          logs:
            type: emptyDir

          data:
            type: "persistentVolumeClaim"
            size: "5Gi"
            storageClass: "{{ .Values.storage.ssd }}"

        volume:
          replicas: 3

          resizeHook:
            enabled: false

          dataDirs:
            - name: data
              type: "persistentVolumeClaim"
              size: "5Gi"
              storageClass: "{{ .Values.storageClass.name }}"
        
        filer:
          replicas: 3
          enablePVC: true

          s3:
            enabled: true
            domainName: s3.{{ .Values.domains.external }}
            port: 8333
            allowEmptyFolder: true

          logs:
            type: emptyDir

          data:
            type: "persistentVolumeClaim"
            size: "5Gi"
            storageClass: "{{ .Values.storage.ssd }}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: mordorhome.{{ .Values.domains.external }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 512m
    nginx.ingress.kubernetes.io/client_max_body_size: 512m
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: s3
spec:
  ingressClassName: nginx
  rules:
    - host: "*.s3.{{ .Values.domains.external }}"
      http:
        paths:
          - backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333
            path: /
            pathType: Prefix
    - host: s3.{{ .Values.domains.external }}
      http:
        paths:
          - backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - '*.{{ .Values.domains.external }}'
        - '*.s3.{{ .Values.domains.external }}'
      secretName: wildcard-tls