apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cluster.fullname" . }}-backup-cron
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.schedule }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: {{ include "cluster.fullname" . }}-backup-cron
      labels:
        {{- include "cluster.labels" . | nindent 8 }}
    spec:
      parallelism: 1
      template:
        metadata:
          name: {{ include "cluster.fullname" . }}-backup-cron
          labels:
            {{- include "cluster.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.imageName }}
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.bootstrap.secretName }}
                      key: password
              command:
                - pg_dump
              args:
                - -Fc
                - -h
                - {{ include "cluster.fullname" . }}-r
                - -U
                - {{ .Values.bootstrap.username }}
                - -d
                - {{ .Values.bootstrap.database }}
                - -f
                - /backup/backup.sql
              volumeMounts:
                - name: backup
                  mountPath: /backup
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: {{ include "cluster.fullname" . }}-backup-pvc
          restartPolicy: Never
