apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cluster.fullname" . }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.instances }}
  imageName: {{ .Values.imageName }}

  postgresUID: {{ .Values.postgresUID }}
  postgresGID: {{ .Values.postgresGID }}

  storage:
    size: {{ .Values.storage.size }}
    storageClass: {{ .Values.storage.storageClass }}
  
  bootstrap:
    initdb:
      database: {{ .Values.bootstrap.database }}
      owner: {{ .Values.bootstrap.username }}
      secret:
        name: {{ .Values.bootstrap.secretName }}
      {{- with .Values.bootstrap.postgresInit }}
      postInitSQL:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  {{- with .Values.roles }}
  managed:
    roles:
      {{- toYaml . | nindent 4 }}
  {{- end }}

  postgresql:
    parameters:
      shared_buffers: {{ .Values.shared_buffers }}
  
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  monitoring:
    enablePodMonitor: true

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: preferred