{{- if .Values.pushSecret.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-credentials-{{ include "cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRefs:
    - name: {{ .Values.pushSecret.secretstore }}
      kind: SecretStore
  selector:
    secret:
      name: {{ .Values.bootstrap.secretName }}
  template:
    data:
      password: "{{ `{{ .password }}` }}"
      username: "{{ `{{ .username }}` }}"
      schema: public
      database: {{ .Values.bootstrap.database }}
      hostname: {{ include "cluster.fullname" . }}-rw.{{ .Release.Namespace }}.svc.cluster.local
      readhostname: {{ include "cluster.fullname" . }}-ro.{{ .Release.Namespace }}.svc.cluster.local
      url: postgres://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@{{ include "cluster.fullname" . }}-rw.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.bootstrap.database }}?sslmode=disable&options=-csearch_path%3Dpublic
      readurl: postgres://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@{{ include "cluster.fullname" . }}-ro.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.bootstrap.database }}?sslmode=disable&options=-csearch_path%3Dpublic
  data:
    - match:
        secretKey: readurl
        remoteRef:
          remoteKey: {{ .Values.pushSecret.remoteKey }}
          property: readurl
    - match:
        secretKey: url
        remoteRef:
          remoteKey: {{ .Values.pushSecret.remoteKey }}
          property: url
    - match:
        secretKey: password
        remoteRef:
          remoteKey: {{ .Values.pushSecret.remoteKey }}
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: {{ .Values.pushSecret.remoteKey }}
          property: username
    - match:
        secretKey: database
        remoteRef:
          remoteKey: {{ .Values.pushSecret.remoteKey }}
          property: database
    - match:
        secretKey: hostname
        remoteRef:
          remoteKey: {{ .Values.pushSecret.remoteKey }}
          property: hostname
    - match:
        secretKey: schema
        remoteRef:
          remoteKey: {{ include "cluster.fullname" . }}-postgres-credentials
          property: schema
    - match:
        secretKey: readhostname
        remoteRef:
          remoteKey: {{ include "cluster.fullname" . }}-postgres-credentials
          property: readhostname
---
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pushSecret.remoteKey }}
  namespace: {{ .Release.Namespace }}
data:
    schema: public
    database: {{ .Values.bootstrap.database }}
    username: {{ .Values.bootstrap.username }}
    hostname: {{ include "cluster.fullname" . }}-rw.{{ .Release.Namespace }}.svc.cluster.local
    readhostname: {{ include "cluster.fullname" . }}-ro.{{ .Release.Namespace }}.svc.cluster.local
    urlsuffix: /{{ .Values.bootstrap.database }}?sslmode=disable&options=-csearch_path%3Dpublic