apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" $ }}-docker-private-credentials
  namespace: {{ $.Values.coder.namespace}}
spec:
  secretStoreRef:
    name: {{ $.Values.vault.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: cluster-private-docker-registry
    template:
      type: kubernetes.io/dockerconfigjson
      {{- with $.Values.dockerconfigTemplate }}
      data:
{{ toYaml . | indent 8 }}
      {{- end }}
  data:
    - remoteRef:
        key: DOCKER
        property: PRIVATE_USERNAME
      secretKey: USERNAME
    - remoteRef:
        key: DOCKER
        property: PRIVATE_PASSWORD
      secretKey: PASSWORD
    - remoteRef:
        key: DOCKER
        property: PRIVATE_HOST
      secretKey: HOST
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" $ }}-docker-private-credentials
  namespace: {{ $.Values.coder.workspaces.namespace }}
spec:
  secretStoreRef:
    name: {{ $.Values.vault.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: cluster-private-docker-registry
    template:
      type: kubernetes.io/dockerconfigjson
      {{- with $.Values.dockerconfigTemplate }}
      data:
{{ toYaml . | indent 8 }}
      {{- end }}
  data:
    - remoteRef:
        key: DOCKER
        property: PRIVATE_USERNAME
      secretKey: USERNAME
    - remoteRef:
        key: DOCKER
        property: PRIVATE_PASSWORD
      secretKey: PASSWORD
    - remoteRef:
        key: DOCKER
        property: PRIVATE_HOST
      secretKey: HOST
---
{{- range $pvc := .Values.coder.pvcs -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvc.name }}
  namespace: {{ $.Values.coder.namespace }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: {{ $pvc.storageClassName }}
---
{{- end -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-middleware-database
  namespace: {{ $.Values.coder.namespace}}
spec:
  secretStoreRef:
    name: cluster-readonly-secretstore-kubernetes
    kind: ClusterSecretStore
  target:
    name: coder-middleware-database
  data:
    - secretKey: BUS_URL
      remoteRef:
        key: kubernetes/rabbitmq
        property: url
    - secretKey: CACHE_URL
      remoteRef:
        key: kubernetes/redis
        property: url
---
