apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.gitlabrunner.namespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-gitlabrunner
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.gitlabrunner.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: gitlab-runner
    repoURL: https://charts.gitlab.io
    targetRevision: {{ .Values.gitlabrunner.version }}
    helm:
      releaseName: gitlabrunner
      values: |-
        imagePullSecrets:
          - name: cluster-docker-secret
        
        gitlabUrl: https://src.yusufali.ca
        runnerToken: glrt-ApsSkmytqgzxDq4Cz_RJ

        rbac:
          create: true

          imagePullSecrets:
            - name: cluster-docker-secret

        runners:
          config: |
            [[runners]]
              image_pull_secrets = ["cluster-docker-secret"]
              [runners.kubernetes]
                cpu_request = "500m"
                image_pull_secrets = ["cluster-docker-secret"]