apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.keda.namespace }}
  labels:
    type: system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-keda
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: {{ .Values.keda.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: {{ .Values.keda.version }}
    helm:
      releaseName: keda