apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.longhorn.namespace }}
  labels:
    type: system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: {{ .Values.longhorn.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/target: "mordorhome.yusufali.ca"
spec:
  ingressClassName: nginx
  rules:
    - host: longhorn.k8s.private
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-longhorn
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: {{ .Values.longhorn.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: {{ .Values.longhorn.version }}
    helm:
      releaseName: longhorn
      values: |-
        fullnameOverride: longhorn
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClassReplicaCount: 1
        defaultSettings:
          defaultReplicaCount: 1
---