apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.postgres.namespace }}
  labels:
    type: system
    dockerpublic: okay
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.postgres.namespace }}
spec:
  secretStoreRefs:
    - name: {{ .Values.secretStore.readWriteStore }}
      kind: SecretStore
  selector:
    secret:
      name: postgres-credentials
  template:
    data:
      password: "{{ `{{ .password }}` }}"
      username: "{{ `{{ .username }}` }}"
      hostname: {{ .Values.postgres.releaseName }}-pgpool.{{ .Values.postgres.namespace }}.svc.cluster.local
      url: "postgres://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@{{ .Values.postgres.releaseName }}-pgpool.{{ .Values.postgres.namespace }}.svc.cluster.local"
      fullurl: "postgresql://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@{{ .Values.postgres.releaseName }}-pgpool.{{ .Values.postgres.namespace }}.svc.cluster.local"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres
          property: username
    - match:
        secretKey: hostname
        remoteRef:
          remoteKey: postgres
          property: hostname
    - match:
        secretKey: url
        remoteRef:
          remoteKey: postgres
          property: url
    - match:
        secretKey: fullurl
        remoteRef:
          remoteKey: postgres
          property: fullurl
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.postgres.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.postgres.secretstore }}
    kind: SecretStore
  target:
    name: postgres-credentials
  data:
    - secretKey: username
      remoteRef:
        key: DB_POSTGRES
        property: USERNAME
    - secretKey: postgres-username
      remoteRef:
        key: DB_POSTGRES
        property: USERNAME
    - secretKey: postgres-password
      remoteRef:
        key: DB_POSTGRES
        property:  PASSWORD
    - secretKey: password
      remoteRef:
        key: DB_POSTGRES
        property:  PASSWORD
    - secretKey: repmgr-password
      remoteRef:
        key: DB_POSTGRES
        property:  PASSWORD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-postgres
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: {{ .Values.postgres.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: postgresql-ha
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.postgres.version }}
    helm:
      releaseName: {{ .Values.postgres.releaseName }}
      values: |-
        fullnameOverride: {{ .Values.postgres.releaseName }}

        global:
          imagePullSecrets:
            - name: cluster-docker-public
          postgresql:
            existingSecret: postgres-credentials

        postgresql:
          replicaCount: {{ .Values.postgres.replicaCount }}

          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}

          networkPolicy:
            enabled: false

          extraVolumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: {{ .Values.postgres.shmSize }}
          extraVolumeMounts:
            - name: dshm
              mountPath: /dev/shm

        pgpool:
          networkPolicy:
            enabled: false

        persistence:
          enabled: true
          storageClass: {{ .Values.postgres.storageClass }}

        backup:
          enabled: true
          cronjob:
            concurrencyPolicy: Forbid
            successfulJobsHistoryLimit: 0
            storage:
              storageClass: {{ .Values.postgres.backupStorageClass }}