apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.prometheus.namespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-prometheus
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.prometheus.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: prometheus-community/kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: {{ .Values.prometheus.version }}
    helm:
      releaseName: prometheus
      values: |-
        grafana:
          ingress:
            enabled: true

            ingressClassName: nginx
            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              external-dns.alpha.kubernetes.io/target: "mordorhome.yusufali.ca"

            tls:
              - hosts:
                  - "grafana.yusufali.ca"
                secretName: grafana-ssl-yusufali

            hosts:
              - grafana.yusufali.ca
              - grafana.k8s.private

            persistence:
              type: pvc
              enabled: true
              storageClassName: nfs-onpremise-dynamic
              accessModes:
                - ReadWriteMany
              size: 10Gi
