apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rabbitmq.namespace }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-docker-credentials
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.stores.vault.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: rabbitmq-docker-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      {{- with $.Values.dockerconfigTemplate }}
      data:
{{ toYaml . | indent 8 }}
      {{- end }}
  data:
    - remoteRef:
        key: DOCKER
        property:  PUBLIC_USERNAME 
      secretKey: USERNAME
    - remoteRef:
        key: DOCKER
        property:  PUBLIC_PASSWORD 
      secretKey: PASSWORD
    - remoteRef:
        key: DOCKER
        property: PUBLIC_HOST
      secretKey: HOST
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.stores.vault.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: rabbitmq-credentials
  data:
    - secretKey: rabbitmq-erlang-cookie 
      remoteRef:
        key: RABBITMQ
        property: rabbitmq-erlang-cookie 
    - secretKey: rabbitmq-password 
      remoteRef:
        key: RABBITMQ
        property:  rabbitmq-password 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-rabbitmq
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: {{ .Values.rabbitmq.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.rabbitmq.version }}
    helm:
      releaseName: {{ .Values.rabbitmq.releaseName }}
      values: |-
        fullnameOverride: {{ .Values.rabbitmq.releaseName }}
        replicaCount: {{ .Values.rabbitmq.replicaCount }}

        image:
          pullSecrets:
            - name: rabbitmq-docker-credentials

        auth:
          username: user
          auth:
            existingPasswordSecret: rabbitmq-credentials
            existingErlangSecret: rabbitmq-credentials

        clustering:
          rebalance: true

        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Delete

        resources:
          {{- toYaml .Values.rabbitmq.resources | nindent 10 }}

        serviceAccount:
          create: false

        networkPolicy:
          enabled: false

        persistence:
          storageClass: {{ .Values.rabbitmq.storageClass }}
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Delete

        ingress:
          enabled: true
          hostname: rabbitmq.k8s.private
          ingressClassName: nginx
        
        ulimitNofiles: ""