apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.redis.namespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-redis
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: {{ .Values.redis.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: redis-cluster
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.redis.version }}
    helm:
      releaseName: redis
      values: |-
        usePassword: false

        redis:
          resources:
            requests:
              memory: 128Mi

        cluster:
          nodes: 3
          replicas: 0

        serviceAccount:
          create: false

        persistence:
          storageClass: nfs-onpremise-dynamic