---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-redis
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "default"
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: redis-cluster
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.redis.version }}
    helm:
      releaseName: redis
      values: |-
        password: test
        persistence:
          enabled: false

        cluster:
          nodes: 3
          replicas: 0

          update:
            currentNumberOfNodes: 3
            currentNumberOfReplicas: 0

        redis:
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          
          configmap: |
            maxmemory 510mb
            maxmemory-policy allkeys-lru