---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-htpasswd
  namespace: {{ .Values.registry.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.registry.secretstore }}
    kind: SecretStore
  target:
    name: registry-htpasswd
    template:
      type: Opaque
      {{- with $.Values.htpasswdTemplate }}
      data:
{{ toYaml . | indent 8 }}
      {{- end }}
  data:
    - remoteRef:
        key: DOCKER_PRIVATE
        property: username
      secretKey: PRIVATE_USERNAME
    - remoteRef:
        key: DOCKER_PRIVATE
        property: password
      secretKey: PRIVATE_PASSWORD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }}-registry
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: {{ .Values.registry.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: charts/helm
    repoURL: https://github.com/drgroot/kubespray.git
    targetRevision: HEAD
    helm:
      releaseName: registry
      values: |-
        fullnameOverride: registry

        image:
          name: registry
          tag: latest

        env:
          - name: REGISTRY_AUTH
            value: "htpasswd"
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: "/auth/htpasswd"
          - name: REGISTRY_STORAGE_MAINTENANCE
            value: |
              uploadpurging:
                enabled: true
                age: 48h
                interval: 24h
                dryrun: false
              readonly:
                enabled: false
              delete:
                enabled: true

        ports:
          - name: port-5000
            containerPort: 5000

        service:
          ports:
            - name: port-5000
              port: 5000
              targetPort: 5000
        
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/client-body-buffer-size: 5000m
            nginx.ingress.kubernetes.io/proxy-body-size: 5000m
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            external-dns.alpha.kubernetes.io/target: "mordorhome.yusufali.ca"
          tls:
            - hosts:
                - "*.yusufali.ca"
              secretName: wildcard-yusufali
          hosts:
            - host: registry.yusufali.ca
              paths:
                - path: /
                  pathType: Prefix

        podSecurityContext:
          runAsUser: 1000
          runAsGroup: 1000

        volumeMounts:
          - name: config
            mountPath: /var/lib/registry
          - mountPath: /auth
            name: htpasswd

        pvc:
          enabled: true
          name: config
          storageClass: {{ .Values.registry.storageClass }}
        volumes:
          - name: htpasswd
            secret:
              secretName: registry-htpasswd