---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: tenant-repo-credentials
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: https://git.yusufali.ca/
        username: '{{ printf "{{ .USERNAME }}" }}'
        password: '{{ printf "{{ .PASSWORD }}" }}'
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: GIT
        property: GIT_PASSWORD
    - secretKey: USERNAME
      remoteRef:
        key: GIT
        property: GIT_USERNAME
---
{{- range $tenant := .Values.tenants }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-{{ $tenant.namespace }}-project
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: {{ $tenant.namespace }}
      server: https://kubernetes.default.svc
  syncWindows:
    - schedule: "0 */4 * * *"
      duration: 1h
      namespaces:
        - {{ $tenant.namespace }}
      applications:
        - "*"
      clusters:
        - "*"
      kind: "allow"
      manualSync: true
  clusterResourceBlacklist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: rbac.authorization.k8s.io
      kind: '*'
    - group: authentication.k8s.io
      kind: '*'
    - group: authorization.k8s.io
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-{{ $tenant.namespace }}-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tenant-{{ $tenant.namespace }}-project
  source:
    repoURL: https://git.yusufali.ca/infra/projects.git
    targetRevision: HEAD
    path: {{ $tenant.namespace }}
    helm:
      releaseName: {{ $tenant.namespace }}
      values: |
        namespace: {{ $tenant.namespace }}
        argoproject: tenant-{{ $tenant.namespace }}-project
        spec:
          project: tenant-{{ $tenant.namespace }}-project
  destination:
    name: ""
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- range $path := $tenant.flags }}
---
{{- if contains ":" $path }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-{{ $tenant.namespace }}-{{ splitList ":" $path | first }}
  namespace: {{ $tenant.namespace }}
spec:
  secretStoreRef:
    name: kubernetes
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: cluster-{{ $tenant.namespace }}-{{ splitList ":" $path | first }}
  dataFrom:
    - extract:
        key: {{ splitList ":" $path | first }}
{{- else if contains "DOCKER_" $path }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" $ }}-{{ $tenant.namespace }}-{{ $path | lower }}
  namespace: {{ $tenant.namespace }}
spec:
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: cluster-{{ $path | lower }}
  dataFrom:
    - extract:
        key: {{ $path }}
{{- end }}
---
{{- end }}
{{- end }}