namespace: test
project: myproject

versions:
  nfsprovisioner: 

storageClass:
  nfsprovisioner: 4.0.18
  name: lake
  hostname: 192.168.1.3
  mountPath: /lake

domains:
  internal: example.com
  external: example.com
  servc: example.com