namespace: test
project: myproject

versions:
  nfsprovisioner: 4.0.18
  seaweedfs: 4.0.379

storageClass:
  name: lake
  hostname: 192.168.1.3
  mountPath: /lake

storage:
  default: default
  backup: default
  ssd: default

domains:
  internal: example.com
  external: example.com
  servc: example.com