---
kind: pipeline
type: kubernetes
name: app

steps:
- name: lint
  image: alpine/helm
  commands:
  - helm lint . --values values.yaml --with-subcharts

- name: template
  image: alpine/helm
  commands:
  - helm template .