# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
replicaCount: 1

nodeName: false
affinity: {}

image:
  name: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  prefix: ""
  suffix: ""

labels: {}

imagePullSecrets: []
# serviceAccountName: my sa

volumeMounts: []
volumes: []

env: []
envFrom: []

service:
  enabled: true
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

sideCars: []
initContainers: []

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

tolerations: []

probes: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: myhostname.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

pvc:
  enabled: false
  name: my-pvc
  storageClass: nfs-nas
  annotations: {}
  storage: 20Gi

  backup:
    enabled: false
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    cron: "0 * * * *"
    port: 19999
    image: registry.yusufali.ca/containers/backup-pvc
    volumeMounts:
      - mountPath: /config
      - mountPath: /data
        subPath: hi
    env:
      - name: DATABASES
        value: ''
      - name: FILES
        value: ''
      - name: FOLDERS
        value: ''