{{- range $task := .Values.tasks.configs }}
{{- range $server := $.Values.storage }}
{{- range $folder := $server.folders }}
{{- if (index $folder $task.name) }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "nfs.fullname" $ }}-{{ $task.name }}-{{ $server.name }}-{{ $folder.name }}
  namespace: {{ $.Values.spec.destination.namespace }}
  labels:
    {{- include "nfs.labels" $ | nindent 4 }}
    task: {{ $task.name }}
    server: {{ $server.name }}
    folder: {{ $folder.name }}
spec:
  schedule: {{ $task.cron | default "0 3 * * *" | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: {{ include "nfs.fullname" $ }}-{{ $task.name }}-{{ $server.name }}-{{ $folder.name }}
      labels:
        {{- include "nfs.labels" $ | nindent 8 }}
        task: {{ $task.name }}
        server: {{ $server.name }}
        folder: {{ $folder.name }}
    spec:
      template:
        metadata:
          name: {{ include "nfs.fullname" $ }}-{{ $task.name }}-{{ $server.name }}-{{ $folder.name }}
          labels:
            {{- include "nfs.labels" $ | nindent 12 }}
            task: {{ $task.name }}
            server: {{ $server.name }}
            folder: {{ $folder.name }}
        spec:
          restartPolicy: Never
          {{ if gt (len $.Values.imageSecrets.chart) 0 }}
          imagePullSecrets:
            {{- range $imageSecret := $.Values.imageSecrets.chart }}
            - name: {{ include "nfs.fullname" $ }}-{{ $imageSecret }}
            {{- end }}
          {{ end }}
          containers:
            - name: task
              image: {{ default $task.image $.Values.tasks.image }}
              {{- with $task.command }}
              command:
              {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with $task.args }}
              args:
              {{ toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: RCLONE_CONFIG_PATH
                  value: /rclone/rclone.conf
              {{- with $task.env }}
              {{ toYaml . | nindent 16 }}
              {{- end }}
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
              volumeMounts:
                {{ range $secret := $task.secrets }}
                {{ if and (hasKey $secret "mount") ($secret.mount) }}
                - name: {{ $secret.name }}
                  mountPath: /{{ $secret.name }}
                {{ end }}
                {{ end }}
                - name: source
                  mountPath: /source
                  subPath: {{ $folder.name }}
              {{- with $task.volumeMounts }}
              {{ toYaml . | nindent 16}}
              {{- end }}
          volumes:
            {{ range $secret := $task.secrets }}
            {{ if and (hasKey $secret "mount") ($secret.mount) }}
            - name: {{ $secret.name }}
              secret:
                defaultMode: 0755
                secretName: {{ include "nfs.fullname" $ }}-{{ $secret.name }}
            {{ end }}  
            {{ end }}
            - name: source
              nfs:
                server: {{ $server.hostname }}
                path: {{ $server.mount_path }}
            {{- with $task.volumes }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}