{{- range $secretName, $properties := .Values.secrets -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nfs.fullname" $ }}-{{ $secretName }}
  namespace: {{ $.Values.spec.destination.namespace }}
spec:
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    creationPolicy: {{ $properties.creationPolicy | default "Owner" }}
    name: {{ $secretName }}
    template:
      engineVersion: v2
      type: {{ $properties.type | default "Opaque" }}
      {{- with $properties.template }}
      data: 
{{ toYaml . | indent 8 }}
      {{- end }}
  data:
  {{ range $data := $properties.data }}
    - secretKey: {{ $data.name | default $data.property }}
      remoteRef:
        key: {{ $data.key }}
        property: {{ $data.property }}
  {{ end }}
---
{{- end -}}