on:
  push:
    branches:
      - master

jobs:
  reset-cluster:
    runs-on: self-hosted
    environment:
      name: remove.prod
      url: https://git.yusufali.ca
    steps:
      - name: clean ssh hosts
        run: rm -rf ~/.ssh

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install packages
        run: pip install -r requirements.txt

      - name: deploy changes
        run: |
          rm kubespray/playbooks/roles || true
          ln -s ../roles kubespray/playbooks/roles
          ansible-playbook -i inventory/sample/hosts.yaml kubespray/reset.yml -b -v --private-key /inventory/id_rsa -e reset_confirmation=yes
