on:
  pull_request_target:
    branches:
      - master
  push:

jobs:
  terraformk8s:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - run: terraform -chdir=terraform init
      - run: terraform -chdir=terraform plan -no-color -input=false -state=/inventory/terraform/state.tfstate -var-file="/inventory/variables.tfvars"

      - if: github.ref == 'refs/heads/master'
        run: terraform -chdir=terraform apply -auto-approve -input=false -state=/inventory/terraform/state.tfstate -var-file="/inventory/variables.tfvars"
